type EmployeeData = {
  [domainId: string]: {
    associateName: string
    function: string
    teamLead: string
    functionalLeader: string
  }
}

const excelData: EmployeeData = {
  AL52569: {
    associateName: "., Shivani",
    function: "DDO",
    teamLead: "Adhikary, Gopa",
    functionalLeader: "Ravindran, Arun Raj",
  },
  AL55429: {
    associateName: "Chitturi, Pratyusha",
    function: "DDO",
    teamLead: "Adhikary, Gopa",
    functionalLeader: "Ravindran, Arun Raj",
  },
  AL55431: {
    associateName: "Vuskamuri, Manasa",
    function: "DDO",
    teamLead: "Adhikary, Gopa",
    functionalLeader: "Ravindran, Arun Raj",
  },
  AL55432: {
    associateName: "Bhoopathi, Rohith",
    function: "DDO",
    teamLead: "Adhikary, Gopa",
    functionalLeader: "Ravindran, Arun Raj",
  },
  AL54471: {
    associateName: "Manisha, Joganpalli",
    function: "DDO",
    teamLead: "Adhikary, Gopa",
    functionalLeader: "Ravindran, Arun Raj",
  },
  AL55421: {
    associateName: "Mahipal Reddy, Baddipadige",
    function: "DDO",
    teamLead: "Adhikary, Gopa",
    functionalLeader: "Ravindran, Arun Raj",
  },
  AL54486: {
    associateName: "Ahmed, Mohammed zubair",
    function: "DDO",
    teamLead: "Adhikary, Gopa",
    functionalLeader: "Ravindran, Arun Raj",
  },
  AH54998: {
    associateName: "M, Sneha",
    function: "DDO",
    teamLead: "Adhikary, Gopa",
    functionalLeader: "Ravindran, Arun Raj",
  },
  AL54658: {
    associateName: "ALEKHYA, TALABHAKTULA",
    function: "DDO",
    teamLead: "Adhikary, Gopa",
    functionalLeader: "Ravindran, Arun Raj",
  },
  AL54473: {
    associateName: "Mansurabad, M Nitin (Mansurabad Nitin)",
    function: "DDO",
    teamLead: "Adhikary, Gopa",
    functionalLeader: "Ravindran, Arun Raj",
  },
  AL56366: {
    associateName: "Barupatla, Rajashekar",
    function: "DDO",
    teamLead: "Adhikary, Gopa",
    functionalLeader: "Ravindran, Arun Raj",
  },
  AG54753: {
    associateName: "D, Kiran",
    function: "DDO",
    teamLead: "Adhikary, Gopa",
    functionalLeader: "Ravindran, Arun Raj",
  },
  AL43275: {
    associateName: "Kudari, Harsh ",
    function: "DDO",
    teamLead: "Adhikary, Gopa",
    functionalLeader: "Ravindran, Arun Raj",
  },
  AL57275: {
    associateName: "Kumar, Mutta Shiva",
    function: "DDO",
    teamLead: "Adhikary, Gopa",
    functionalLeader: "Ravindran, Arun Raj",
  },
  AL42043: {
    associateName: "M, Vidya",
    function: "DDO",
    teamLead: "Adhikary, Gopa",
    functionalLeader: "Ravindran, Arun Raj",
  },
  AL55425: {
    associateName: "Garlapati, Vikas",
    function: "DDO",
    teamLead: "Adhikary, Gopa",
    functionalLeader: "Ravindran, Arun Raj",
  },
  AG99030: {
    associateName: "T D, Aishwaraya",
    function: "DDO",
    teamLead: "Adhikary, Gopa",
    functionalLeader: "Ravindran, Arun Raj",
  },
  AG99016: {
    associateName: "S, Saidulu",
    function: "DDO",
    teamLead: "Adhikary, Gopa",
    functionalLeader: "Ravindran, Arun Raj",
  },
  AL66290: {
    associateName: "., Meenakshi",
    function: "PCM",
    teamLead: "Ansari Anjum",
    functionalLeader: "Chatterjee, Anupam",
  },
  AL99289: {
    associateName: " Juganu Varshney",
    function: "PCM",
    teamLead: "Anupam Chatterjee",
    functionalLeader: "Chatterjee, Anupam",
  },
  AD85492: {
    associateName: "Faizul Hasan",
    function: "PCM",
    teamLead: "Anupam Chatterjee",
    functionalLeader: "Chatterjee, Anupam",
  },
  AG84918: {
    associateName: "Gopal Singh",
    function: "PCM",
    teamLead: "Anupam Chatterjee",
    functionalLeader: "Chatterjee, Anupam",
  },
  AH40126: {
    associateName: "G L, Santhosh",
    function: "PCM",
    teamLead: "Anupam Chatterjee",
    functionalLeader: "Chatterjee, Anupam",
  },
  AL47552: {
    associateName: "Ipsa Mohapatra",
    function: "PCM",
    teamLead: "Anupam Chatterjee",
    functionalLeader: "Chatterjee, Anupam",
  },
  AH35461: {
    associateName: "B, Bheem Raj",
    function: "PCM",
    teamLead: "Anupam Chatterjee",
    functionalLeader: "Chatterjee, Anupam",
  },
  AF08215: {
    associateName: "Sunil Gupta",
    function: "PCM",
    teamLead: "Anupam Chatterjee",
    functionalLeader: "Chatterjee, Anupam",
  },
  AL58555: {
    associateName: "Rajani Radhae",
    function: "PCM",
    teamLead: "Anupam Chatterjee",
    functionalLeader: "Chatterjee, Anupam",
  },
  AH33351: {
    associateName: "G, Srikanth Puri",
    function: "PCM",
    teamLead: "Anupam Chatterjee",
    functionalLeader: "Chatterjee, Anupam",
  },
  AG84919: {
    associateName: "Subbarao Pokuri",
    function: "PCM",
    teamLead: "Anupam Chatterjee",
    functionalLeader: "Chatterjee, Anupam",
  },
  AL71586: {
    associateName: "Anupam Pathak",
    function: "PCM",
    teamLead: "Anupam Chatterjee",
    functionalLeader: "Chatterjee, Anupam",
  },
  AL43341: {
    associateName: "Altaf, Shaik",
    function: "PCM",
    teamLead: "Pathak, Anupam",
    functionalLeader: "Chatterjee, Anupam",
  },
  AL42310: {
    associateName: "G, Anitha Devi (Anitha)",
    function: "Rosters",
    teamLead: "Aruchamy, Karuppusamy",
    functionalLeader: "Muralidharan, TamilEnian",
  },
  AL65303: {
    associateName: "., Himani",
    function: "Rosters",
    teamLead: "Aruchamy, Karuppusamy",
    functionalLeader: "Muralidharan, TamilEnian",
  },
  AL60122: {
    associateName: "., Mansi (Mansi)",
    function: "Rosters",
    teamLead: "Aruchamy, Karuppusamy",
    functionalLeader: "Muralidharan, TamilEnian",
  },
  AL64366: {
    associateName: "Kumari, Kajal",
    function: "Rosters",
    teamLead: "Aruchamy, Karuppusamy",
    functionalLeader: "Muralidharan, TamilEnian",
  },
  AL64333: {
    associateName: "PRASHAR, HIMANSHU",
    function: "Rosters",
    teamLead: "Aruchamy, Karuppusamy",
    functionalLeader: "Muralidharan, TamilEnian",
  },
  AL66128: {
    associateName: "Negi, Swati",
    function: "Rosters",
    teamLead: "Aruchamy, Karuppusamy",
    functionalLeader: "Muralidharan, TamilEnian",
  },
  AL66035: {
    associateName: "Saxena, Tanya",
    function: "Rosters",
    teamLead: "Aruchamy, Karuppusamy",
    functionalLeader: "Muralidharan, TamilEnian",
  },
  AL65785: {
    associateName: "Thakur, Neha",
    function: "Rosters",
    teamLead: "Aruchamy, Karuppusamy",
    functionalLeader: "Muralidharan, TamilEnian",
  },
  AL42346: {
    associateName: "A, Esha Pandey",
    function: "Rosters",
    teamLead: "Aruchamy, Karuppusamy",
    functionalLeader: "Muralidharan, TamilEnian",
  },
  AL42980: {
    associateName: "Jayanth, S",
    function: "Rosters",
    teamLead: "Aruchamy, Karuppusamy",
    functionalLeader: "Muralidharan, TamilEnian",
  },
  AL44125: {
    associateName: "Yalagukar, Vidyanand",
    function: "Rosters",
    teamLead: "Aruchamy, Karuppusamy",
    functionalLeader: "Muralidharan, TamilEnian",
  },
  AL43981: {
    associateName: "Anant Naik, Soumya",
    function: "Rosters",
    teamLead: "Aruchamy, Karuppusamy",
    functionalLeader: "Muralidharan, TamilEnian",
  },
  AL43971: {
    associateName: ", Deepak Y",
    function: "Rosters",
    teamLead: "Aruchamy, Karuppusamy",
    functionalLeader: "Muralidharan, TamilEnian",
  },
  AL43976: {
    associateName: "S, NAZEER",
    function: "Rosters",
    teamLead: "Aruchamy, Karuppusamy",
    functionalLeader: "Muralidharan, TamilEnian",
  },
  AL43978: {
    associateName: "Patil, Praveen",
    function: "Rosters",
    teamLead: "Aruchamy, Karuppusamy",
    functionalLeader: "Muralidharan, TamilEnian",
  },
  AL43096: {
    associateName: "A, Venkatesha (Amaravathi Venkatesha A)",
    function: "Rosters",
    teamLead: "Aruchamy, Karuppusamy",
    functionalLeader: "Muralidharan, TamilEnian",
  },
  AL44129: {
    associateName: "Takale, Ankusha",
    function: "Rosters",
    teamLead: "Aruchamy, Karuppusamy",
    functionalLeader: "Muralidharan, TamilEnian",
  },
  AL44181: {
    associateName: "Vignesh, P",
    function: "Rosters",
    teamLead: "Aruchamy, Karuppusamy",
    functionalLeader: "Muralidharan, TamilEnian",
  },
  AL43274: {
    associateName: "Pareek, Pratham",
    function: "Rosters",
    teamLead: "Aruchamy, Karuppusamy",
    functionalLeader: "Muralidharan, TamilEnian",
  },
  AL79033: {
    associateName: "Venkatesh, Nirmal Kumar",
    function: "Rosters",
    teamLead: "Aruchamy, Karuppusamy",
    functionalLeader: "Muralidharan, TamilEnian",
  },
  AL43289: {
    associateName: "Moger, Mandara",
    function: "Rosters",
    teamLead: "Aruchamy, Karuppusamy",
    functionalLeader: "Muralidharan, TamilEnian",
  },
  AL46449: {
    associateName: "G, PRAVEEN",
    function: "Rosters",
    teamLead: "Aruchamy, Karuppusamy",
    functionalLeader: "Muralidharan, TamilEnian",
  },
  AL72858: {
    associateName: "Singh, Sakshi",
    function: "Provider Enrollment",
    teamLead: "Badoni, Sukesh",
    functionalLeader: "Chatterjee, Anupam",
  },
  AL64165: {
    associateName: "Kumar, Prabhat",
    function: "Provider Enrollment",
    teamLead: "Badoni, Sukesh",
    functionalLeader: "Chatterjee, Anupam",
  },
  AL67796: {
    associateName: "Bisht, Bhagyashree",
    function: "Provider Enrollment",
    teamLead: "Badoni, Sukesh",
    functionalLeader: "Chatterjee, Anupam",
  },
  AL72879: {
    associateName: "Sahu, Smaranika",
    function: "Provider Enrollment",
    teamLead: "Badoni, Sukesh",
    functionalLeader: "Chatterjee, Anupam",
  },
  AL67802: {
    associateName: "Shakya, Sakshi",
    function: "Provider Enrollment",
    teamLead: "Badoni, Sukesh",
    functionalLeader: "Chatterjee, Anupam",
  },
  AL72874: {
    associateName: "Shinde, Manjushri",
    function: "Provider Enrollment",
    teamLead: "Badoni, Sukesh",
    functionalLeader: "Chatterjee, Anupam",
  },
  AL67797: {
    associateName: "Singh, Manu",
    function: "Provider Enrollment",
    teamLead: "Badoni, Sukesh",
    functionalLeader: "Chatterjee, Anupam",
  },
  AL67806: {
    associateName: "Arora, Chahat",
    function: "Provider Enrollment",
    teamLead: "Badoni, Sukesh",
    functionalLeader: "Chatterjee, Anupam",
  },
  AL67704: {
    associateName: "Tandon, Priyanshi",
    function: "Provider Enrollment",
    teamLead: "Badoni, Sukesh",
    functionalLeader: "Chatterjee, Anupam",
  },
  AL67803: {
    associateName: "Tiwari, Beauty",
    function: "Provider Enrollment",
    teamLead: "Badoni, Sukesh",
    functionalLeader: "Chatterjee, Anupam",
  },
  AL67800: {
    associateName: "., Uma",
    function: "Provider Enrollment",
    teamLead: "Badoni, Sukesh",
    functionalLeader: "Chatterjee, Anupam",
  },
  AL64563: {
    associateName: "Junaid, Mohd",
    function: "Provider Enrollment",
    teamLead: "Badoni, Sukesh",
    functionalLeader: "Chatterjee, Anupam",
  },
  AL64564: {
    associateName: "Aimol, Chaithu",
    function: "Provider Enrollment",
    teamLead: "Badoni, Sukesh",
    functionalLeader: "Chatterjee, Anupam",
  },
  AL64373: {
    associateName: "Yadav, Akash",
    function: "Provider Enrollment",
    teamLead: "Badoni, Sukesh",
    functionalLeader: "Chatterjee, Anupam",
  },
  AL60049: {
    associateName: "Adlakha, Chirag",
    function: "Provider Enrollment",
    teamLead: "Badoni, Sukesh",
    functionalLeader: "Chatterjee, Anupam",
  },
  AL64377: {
    associateName: "Patel, Vishal",
    function: "Provider Enrollment",
    teamLead: "Badoni, Sukesh",
    functionalLeader: "Chatterjee, Anupam",
  },
  AH76357: {
    associateName: "N T, Rajesh",
    function: "Provider Enrollment",
    teamLead: "Badoni, Sukesh",
    functionalLeader: "Chatterjee, Anupam",
  },
  AH72421: {
    associateName: "Patel, Rahul",
    function: "Provider Enrollment",
    teamLead: "Badoni, Sukesh",
    functionalLeader: "Chatterjee, Anupam",
  },
  AL73313: {
    associateName: "Gupta, Payal",
    function: "Provider Enrollment",
    teamLead: "Badoni, Sukesh",
    functionalLeader: "Chatterjee, Anupam",
  },
  AL72873: {
    associateName: "Jena, Sushila Gayatri",
    function: "Provider Enrollment",
    teamLead: "Badoni, Sukesh",
    functionalLeader: "Chatterjee, Anupam",
  },
  AG54758: {
    associateName: "D.k, Girish",
    function: "Provider Enrollment",
    teamLead: "Badoni, Sukesh",
    functionalLeader: "Chatterjee, Anupam",
  },
  AL59942: {
    associateName: "Kumar, Vishal",
    function: "Provider Enrollment",
    teamLead: "Badoni, Sukesh",
    functionalLeader: "K v s, Deepa",
  },
  AL67798: {
    associateName: "Singh, Tripti",
    function: "Provider Enrollment",
    teamLead: "Badoni, Sukesh",
    functionalLeader: "K v s, Deepa",
  },
  AL55588: {
    associateName: "G B, Anjali",
    function: "Rosters",
    teamLead: "Biraiah, DEEPAK",
    functionalLeader: "Muralidharan, TamilEnian",
  },
  AL56462: {
    associateName: "Konduru, DEEPIKA",
    function: "Rosters",
    teamLead: "Biraiah, DEEPAK",
    functionalLeader: "Muralidharan, TamilEnian",
  },
  AL65165: {
    associateName: "., Neha",
    function: "Rosters",
    teamLead: "Biraiah, DEEPAK",
    functionalLeader: "Muralidharan, TamilEnian",
  },
  AL45175: {
    associateName: "Chalageri, Lavanya",
    function: "Rosters",
    teamLead: "Biraiah, DEEPAK",
    functionalLeader: "Muralidharan, TamilEnian",
  },
  AL53453: {
    associateName: "K, Bharadwaj",
    function: "Rosters",
    teamLead: "Biraiah, DEEPAK",
    functionalLeader: "Muralidharan, TamilEnian",
  },
  AL53321: {
    associateName: "Nekar, Anitha",
    function: "Rosters",
    teamLead: "Biraiah, DEEPAK",
    functionalLeader: "Muralidharan, TamilEnian",
  },
  AL56205: {
    associateName: "A, Siddiq",
    function: "Rosters",
    teamLead: "Biraiah, DEEPAK",
    functionalLeader: "Muralidharan, TamilEnian",
  },
  AL46048: {
    associateName: "BR, Keerthana (Keerthana BR)",
    function: "Rosters",
    teamLead: "Biraiah, DEEPAK",
    functionalLeader: "Muralidharan, TamilEnian",
  },
  AL44714: {
    associateName: "R, shilpa",
    function: "Rosters",
    teamLead: "Biraiah, DEEPAK",
    functionalLeader: "Muralidharan, TamilEnian",
  },
  AL46046: {
    associateName: "Bagoji, Rashmi (Bagoji Rashmi)",
    function: "Rosters",
    teamLead: "Biraiah, DEEPAK",
    functionalLeader: "Muralidharan, TamilEnian",
  },
  AL44864: {
    associateName: "Boopathy P, Mahendra",
    function: "Rosters",
    teamLead: "Biraiah, DEEPAK",
    functionalLeader: "Muralidharan, TamilEnian",
  },
  AL56210: {
    associateName: "E, Shruthi",
    function: "Rosters",
    teamLead: "Biraiah, DEEPAK",
    functionalLeader: "Muralidharan, TamilEnian",
  },
  AL52929: {
    associateName: "Eesarla, Phanindra",
    function: "Rosters",
    teamLead: "Biraiah, DEEPAK",
    functionalLeader: "Muralidharan, TamilEnian",
  },
  AL56358: {
    associateName: "G, Prasanna Kumar",
    function: "Rosters",
    teamLead: "Biraiah, DEEPAK",
    functionalLeader: "Muralidharan, TamilEnian",
  },
  AL55368: {
    associateName: "Gowda M, Manohar",
    function: "Rosters",
    teamLead: "Biraiah, DEEPAK",
    functionalLeader: "Muralidharan, TamilEnian",
  },
  AL52948: {
    associateName: "Honnalli, Sanjay (Honnalli Sanjay)",
    function: "Rosters",
    teamLead: "Biraiah, DEEPAK",
    functionalLeader: "Muralidharan, TamilEnian",
  },
  AL43479: {
    associateName: "L, BHOOMIKA",
    function: "Rosters",
    teamLead: "Biraiah, DEEPAK",
    functionalLeader: "Muralidharan, TamilEnian",
  },
  AL65803: {
    associateName: "LNU, Bhawna",
    function: "Rosters",
    teamLead: "Biraiah, DEEPAK",
    functionalLeader: "Muralidharan, TamilEnian",
  },
  AL45961: {
    associateName: "M, Madhushree",
    function: "Rosters",
    teamLead: "Biraiah, DEEPAK",
    functionalLeader: "Muralidharan, TamilEnian",
  },
  AL55568: {
    associateName: "Maruti Honnegundi, Vinay",
    function: "Rosters",
    teamLead: "Biraiah, DEEPAK",
    functionalLeader: "Muralidharan, TamilEnian",
  },
  AL56364: {
    associateName: "N, Yashaswini",
    function: "Rosters",
    teamLead: "Biraiah, DEEPAK",
    functionalLeader: "Muralidharan, TamilEnian",
  },
  AL53454: {
    associateName: "Nandigavi, Basavaraj",
    function: "Rosters",
    teamLead: "Biraiah, DEEPAK",
    functionalLeader: "Muralidharan, TamilEnian",
  },
  AL55347: {
    associateName: "S, Srikanth",
    function: "Rosters",
    teamLead: "Biraiah, DEEPAK",
    functionalLeader: "Muralidharan, TamilEnian",
  },
  AL64180: {
    associateName: "Singh, Ajitesh",
    function: "Rosters",
    teamLead: "Biraiah, DEEPAK",
    functionalLeader: "Muralidharan, TamilEnian",
  },
  AL65164: {
    associateName: "Singh, Anjali",
    function: "Rosters",
    teamLead: "Biraiah, DEEPAK",
    functionalLeader: "Muralidharan, TamilEnian",
  },
  AL44701: {
    associateName: "Sushma, K",
    function: "Rosters",
    teamLead: "Biraiah, DEEPAK",
    functionalLeader: "Muralidharan, TamilEnian",
  },
  AL55363: {
    associateName: "V, Srinivas",
    function: "Rosters",
    teamLead: "Biraiah, DEEPAK",
    functionalLeader: "Muralidharan, TamilEnian",
  },
  AL52181: {
    associateName: "Kandasamy, Krishnakumar",
    function: "L&D Offshore",
    teamLead: "Bn, Aparna",
    functionalLeader: "Bn, Aparna",
  },
  AG89427: {
    associateName: "Anupam Chatterjee",
    function: "PCM",
    teamLead: "Bn, Aparna",
    functionalLeader: "Chatterjee, Anupam",
  },
  AL53072: {
    associateName: "K v s, Deepa",
    function: "Rosters",
    teamLead: "Bn, Aparna",
    functionalLeader: "K v s, Deepa",
  },
  AG25559: {
    associateName: "Biradar, Tejpal S",
    function: "Rosters",
    teamLead: "Bn, Aparna",
    functionalLeader: "K v s, Deepa",
  },
  AH25199: {
    associateName: "Muralidharan, TamilEnian",
    function: "Rosters",
    teamLead: "Bn, Aparna",
    functionalLeader: "Muralidharan, TamilEnian",
  },
  AL66322: {
    associateName: "Ravindran, Arun Raj",
    function: "DDO",
    teamLead: "Bn, Aparna",
    functionalLeader: "Ravindran, Arun Raj",
  },
  AL67308: {
    associateName: "Guttula, Sreenivas",
    function: "PCM",
    teamLead: "Chatterjee, Anupam",
    functionalLeader: "Chatterjee, Anupam",
  },
  AL54477: {
    associateName: "Kumar, Nirmal",
    function: "PCM",
    teamLead: "Chatterjee, Anupam",
    functionalLeader: "Chatterjee, Anupam",
  },
  AL60653: {
    associateName: "Badoni, Sukesh",
    function: "PCM",
    teamLead: "Chatterjee, Anupam",
    functionalLeader: "Chatterjee, Anupam",
  },
  AG62599: {
    associateName: "B, Raj Kumar",
    function: "PCM",
    teamLead: "Chatterjee, Anupam",
    functionalLeader: "Chatterjee, Anupam",
  },
  AL54650: {
    associateName: "Akshata Merawade",
    function: "PCM",
    teamLead: "Chatterjee, Anupam",
    functionalLeader: "Chatterjee, Anupam",
  },
  AL66400: {
    associateName: "Anika Maheshwari",
    function: "PCM",
    teamLead: "Chatterjee, Anupam",
    functionalLeader: "Chatterjee, Anupam",
  },
  AG98900: {
    associateName: "N, Swetha",
    function: "L&D Offshore",
    teamLead: "Chatterjee, Anupam",
    functionalLeader: "Kandasamy, Krishnakumar",
  },
  AH72510: {
    associateName: "Raj, Shreya V",
    function: "L&D Offshore",
    teamLead: "Chatterjee, Anupam",
    functionalLeader: "Kandasamy, Krishnakumar",
  },
  AL53042: {
    associateName: "Addula, Madhumitha Reddy",
    function: "Rosters",
    teamLead: "Chava, Kiran Kumar",
    functionalLeader: "K v s, Deepa",
  },
  AL53662: {
    associateName: "Challaram, Chaitra",
    function: "Rosters",
    teamLead: "Chava, Kiran Kumar",
    functionalLeader: "K v s, Deepa",
  },
  AL53657: {
    associateName: "Kairamkonda, Arun netha (Kairamkonda Arun netha)",
    function: "Rosters",
    teamLead: "Chava, Kiran Kumar",
    functionalLeader: "K v s, Deepa",
  },
  AL54662: {
    associateName: "Noman, Mohd (Mohd Noman)",
    function: "Rosters",
    teamLead: "Chava, Kiran Kumar",
    functionalLeader: "K v s, Deepa",
  },
  AL54470: {
    associateName: "Pasha, Afzal",
    function: "Rosters",
    teamLead: "Chava, Kiran Kumar",
    functionalLeader: "K v s, Deepa",
  },
  AL54130: {
    associateName: "Rohit, Kale",
    function: "Rosters",
    teamLead: "Chava, Kiran Kumar",
    functionalLeader: "K v s, Deepa",
  },
  AL54459: {
    associateName: "Sai Prasanth, Kosaraju",
    function: "Rosters",
    teamLead: "Chava, Kiran Kumar",
    functionalLeader: "K v s, Deepa",
  },
  AL53462: {
    associateName: "Shalom, Hanamkonda Sharly",
    function: "Rosters",
    teamLead: "Chava, Kiran Kumar",
    functionalLeader: "K v s, Deepa",
  },
  AL55422: {
    associateName: "SINGH, ANKIT KUMAR",
    function: "Rosters",
    teamLead: "Chava, Kiran Kumar",
    functionalLeader: "K v s, Deepa",
  },
  AL54040: {
    associateName: "Sree Hari, Kadiri",
    function: "Rosters",
    teamLead: "Chava, Kiran Kumar",
    functionalLeader: "K v s, Deepa",
  },
  AL53525: {
    associateName: "Timmaraju, Jahnavi",
    function: "Rosters",
    teamLead: "Chava, Kiran Kumar",
    functionalLeader: "K v s, Deepa",
  },
  AL52959: {
    associateName: "Veerabhathini, Surya",
    function: "Rosters",
    teamLead: "Chava, Kiran Kumar",
    functionalLeader: "K v s, Deepa",
  },
  AH84987: {
    associateName: "Chambani, Sai Varshitha",
    function: "Rosters",
    teamLead: "Chava, Kiran Kumar",
    functionalLeader: "K v s, Deepa",
  },
  AH22020: {
    associateName: "Vittal, Revathi",
    function: "Rosters",
    teamLead: "Chava, Kiran Kumar",
    functionalLeader: "K v s, Deepa",
  },
  AH85009: {
    associateName: "Gugilla, Venkatesh",
    function: "Rosters",
    teamLead: "Chava, Kiran Kumar",
    functionalLeader: "K v s, Deepa",
  },
  AH07208: {
    associateName: "Sravani, Shrunghari",
    function: "Rosters",
    teamLead: "Chava, Kiran Kumar",
    functionalLeader: "K v s, Deepa",
  },
  AL42364: {
    associateName: "R, BHUMIKA.",
    function: "Re-work",
    teamLead: "Dorepally, Ashwini",
    functionalLeader: "K v s, Deepa",
  },
  AL55519: {
    associateName: "Venkatesh, Odde",
    function: "Provider Enrollment",
    teamLead: "Guttula, Sreenivas",
    functionalLeader: "Chatterjee, Anupam",
  },
  AH59599: {
    associateName: "Shravan, Kothapeta",
    function: "Provider Enrollment",
    teamLead: "Guttula, Sreenivas",
    functionalLeader: "Chatterjee, Anupam",
  },
  AL56464: {
    associateName: "Chavala, Harinath",
    function: "Provider Enrollment",
    teamLead: "Guttula, Sreenivas",
    functionalLeader: "Chatterjee, Anupam",
  },
  AH22007: {
    associateName: "Peroji, Ravalika",
    function: "Provider Enrollment",
    teamLead: "Guttula, Sreenivas",
    functionalLeader: "Chatterjee, Anupam",
  },
  AL43264: {
    associateName: "Bathula, Arvind Kumar",
    function: "Provider Enrollment",
    teamLead: "Guttula, Sreenivas",
    functionalLeader: "Chatterjee, Anupam",
  },
  AH55224: {
    associateName: "Janapatla, Dinesh",
    function: "Provider Enrollment",
    teamLead: "Guttula, Sreenivas",
    functionalLeader: "Chatterjee, Anupam",
  },
  AL55409: {
    associateName: "KUMARI, MATTA DHARANI",
    function: "Provider Enrollment",
    teamLead: "Guttula, Sreenivas",
    functionalLeader: "Chatterjee, Anupam",
  },
  AH22012: {
    associateName: "Achyutha, Rajury",
    function: "Provider Enrollment",
    teamLead: "Guttula, Sreenivas",
    functionalLeader: "Chatterjee, Anupam",
  },
  AH22015: {
    associateName: "Kumar, Diddi Pranay",
    function: "Provider Enrollment",
    teamLead: "Guttula, Sreenivas",
    functionalLeader: "Chatterjee, Anupam",
  },
  AH22006: {
    associateName: "Maniyar, Katyayini",
    function: "Provider Enrollment",
    teamLead: "Guttula, Sreenivas",
    functionalLeader: "Chatterjee, Anupam",
  },
  AG98967: {
    associateName: "Ahammad, Shaik Jubair",
    function: "Provider Enrollment",
    teamLead: "Guttula, Sreenivas",
    functionalLeader: "Chatterjee, Anupam",
  },
  AL43962: {
    associateName: "TANUJA, KUMARI",
    function: "Provider Enrollment",
    teamLead: "Guttula, Sreenivas",
    functionalLeader: "Chatterjee, Anupam",
  },
  AL54458: {
    associateName: "Battula, B Harinath",
    function: "Provider Enrollment",
    teamLead: "Guttula, Sreenivas",
    functionalLeader: "Chatterjee, Anupam",
  },
  AL55343: {
    associateName: "Sowjanya, Mukthedar",
    function: "Provider Enrollment",
    teamLead: "Guttula, Sreenivas",
    functionalLeader: "Chatterjee, Anupam",
  },
  AL54457: {
    associateName: "Yamini, Ganpisetti",
    function: "Provider Enrollment",
    teamLead: "Guttula, Sreenivas",
    functionalLeader: "Chatterjee, Anupam",
  },
  AL44860: {
    associateName: "Koona, Tejashwini",
    function: "Provider Enrollment",
    teamLead: "Guttula, Sreenivas",
    functionalLeader: "Chatterjee, Anupam",
  },
  AH55245: {
    associateName: "Mahesh, Manakar",
    function: "Provider Enrollment",
    teamLead: "Guttula, Sreenivas",
    functionalLeader: "Chatterjee, Anupam",
  },
  AL43961: {
    associateName: "singh, Swapna",
    function: "Provider Enrollment",
    teamLead: "Guttula, Sreenivas",
    functionalLeader: "Chatterjee, Anupam",
  },
  AL55410: {
    associateName: "Undeti, Unike",
    function: "Provider Enrollment",
    teamLead: "Guttula, Sreenivas",
    functionalLeader: "Chatterjee, Anupam",
  },
  AH55239: {
    associateName: "Batna, Devika",
    function: "Provider Enrollment",
    teamLead: "Guttula, Sreenivas",
    functionalLeader: "Chatterjee, Anupam",
  },
  AG98914: {
    associateName: "M, Gopala Krishna",
    function: "Provider Enrollment",
    teamLead: "Guttula, Sreenivas",
    functionalLeader: "Chatterjee, Anupam",
  },
  AH55190: {
    associateName: "Amar, Kaydanaru",
    function: "Provider Enrollment",
    teamLead: "Guttula, Sreenivas",
    functionalLeader: "K v s, Deepa",
  },
  AH55220: {
    associateName: "Pilli, Sravan kumar",
    function: "Provider Enrollment",
    teamLead: "Guttula, Sreenivas",
    functionalLeader: "K v s, Deepa",
  },
  AH76339: {
    associateName: "Gondla, Supriya",
    function: "Provider Enrollment",
    teamLead: "Guttula, Sreenivas",
    functionalLeader: "K v s, Deepa",
  },
  AH57646: {
    associateName: "Naveen, Bejjenki",
    function: "Provider Enrollment",
    teamLead: "Guttula, Sreenivas",
    functionalLeader: "K v s, Deepa",
  },
  AH40753: {
    associateName: "K, Thanushree",
    function: "PCM",
    teamLead: "Ipsa Mohapatra",
    functionalLeader: "Chatterjee, Anupam",
  },
  AG98915: {
    associateName: "Richard, Antino",
    function: "PCM",
    teamLead: "Ipsa Mohapatra",
    functionalLeader: "Chatterjee, Anupam",
  },
  AL67620: {
    associateName: "Deeksha Anand",
    function: "PCM",
    teamLead: "Ipsa Mohapatra",
    functionalLeader: "Chatterjee, Anupam",
  },
  AH33408: {
    associateName: "Gattu, Vinod Kumar",
    function: "PCM",
    teamLead: "Ipsa Mohapatra",
    functionalLeader: "Chatterjee, Anupam",
  },
  AL64363: {
    associateName: "Harsh Jindal",
    function: "PCM",
    teamLead: "Ipsa Mohapatra",
    functionalLeader: "Chatterjee, Anupam",
  },
  AH40820: {
    associateName: "K, Divya",
    function: "PCM",
    teamLead: "Ipsa Mohapatra",
    functionalLeader: "Chatterjee, Anupam",
  },
  AL54660: {
    associateName: "Kavya Yadla",
    function: "PCM",
    teamLead: "Ipsa Mohapatra",
    functionalLeader: "Chatterjee, Anupam",
  },
  AL69194: {
    associateName: "Manisha",
    function: "PCM",
    teamLead: "Ipsa Mohapatra",
    functionalLeader: "Chatterjee, Anupam",
  },
  AL66920: {
    associateName: "Mansi Goswami",
    function: "PCM",
    teamLead: "Ipsa Mohapatra",
    functionalLeader: "Chatterjee, Anupam",
  },
  AL67298: {
    associateName: "Mansi Yadav",
    function: "PCM",
    teamLead: "Ipsa Mohapatra",
    functionalLeader: "Chatterjee, Anupam",
  },
  AL54665: {
    associateName: "Nallanichakravarthula V S J Sai Kumar",
    function: "PCM",
    teamLead: "Ipsa Mohapatra",
    functionalLeader: "Chatterjee, Anupam",
  },
  AL64331: {
    associateName: "Raja Kumar Singh",
    function: "PCM",
    teamLead: "Ipsa Mohapatra",
    functionalLeader: "Chatterjee, Anupam",
  },
  AL72877: {
    associateName: "Sara Suhail",
    function: "PCM",
    teamLead: "Ipsa Mohapatra",
    functionalLeader: "Chatterjee, Anupam",
  },
  AL42047: {
    associateName: "vallepu, ajay",
    function: "PCM",
    teamLead: "Ipsa Mohapatra",
    functionalLeader: "Chatterjee, Anupam",
  },
  AL54654: {
    associateName: "Raju S",
    function: "PCM",
    teamLead: "Ipsa Mohapatra",
    functionalLeader: "Chatterjee, Anupam",
  },
  AL55411: {
    associateName: "Shiva Mallikarjun",
    function: "PCM",
    teamLead: "Ipsa Mohapatra",
    functionalLeader: "Chatterjee, Anupam",
  },
  AL55597: {
    associateName: "Thota Sravani",
    function: "PCM",
    teamLead: "Ipsa Mohapatra",
    functionalLeader: "Chatterjee, Anupam",
  },
  AL55590: {
    associateName: "Chaitra L Joshi",
    function: "PCM",
    teamLead: "Ipsa Mohapatra",
    functionalLeader: "Chatterjee, Anupam",
  },
  AL54659: {
    associateName: "Santosh Fakkirappa Tegginkeri",
    function: "PCM",
    teamLead: "Ipsa Mohapatra",
    functionalLeader: "Chatterjee, Anupam",
  },
  AL54584: {
    associateName: "Bhavani Padmaraju",
    function: "PCM",
    teamLead: "Ipsa Mohapatra",
    functionalLeader: "Chatterjee, Anupam",
  },
  AL55241: {
    associateName: "Jayashree N",
    function: "PCM",
    teamLead: "Ipsa Mohapatra",
    functionalLeader: "Chatterjee, Anupam",
  },
  AL54651: {
    associateName: "Gurkhade Jaishree",
    function: "PCM",
    teamLead: "Ipsa Mohapatra",
    functionalLeader: "Chatterjee, Anupam",
  },
  AH21764: {
    associateName: "Kurmi, Tarun Deepak",
    function: "PCM",
    teamLead: "Ipsa Mohapatra",
    functionalLeader: "Chatterjee, Anupam",
  },
  AM02987: {
    associateName: "Gaurav Gupta",
    function: "PCM",
    teamLead: "Jugnu Varshney",
    functionalLeader: "Chatterjee, Anupam",
  },
  AH43583: {
    associateName: "Thallapureddy, Poojitha",
    function: "PCM",
    teamLead: "Jugnu Varshney",
    functionalLeader: "Chatterjee, Anupam",
  },
  AH40735: {
    associateName: "K A, Divya",
    function: "PCM",
    teamLead: "Jugnu Varshney",
    functionalLeader: "Chatterjee, Anupam",
  },
  AH85855: {
    associateName: "K S, Sanjay",
    function: "PCM",
    teamLead: "Jugnu Varshney",
    functionalLeader: "Chatterjee, Anupam",
  },
  AH40125: {
    associateName: "N S, Sowmya",
    function: "PCM",
    teamLead: "Jugnu Varshney",
    functionalLeader: "Chatterjee, Anupam",
  },
  AL42981: {
    associateName: "Singh, B Vijay",
    function: "PCM",
    teamLead: "Jugnu Varshney",
    functionalLeader: "Chatterjee, Anupam",
  },
  AL54647: {
    associateName: "Gonipalli Venkatesh",
    function: "PCM",
    teamLead: "Jugnu Varshney",
    functionalLeader: "Chatterjee, Anupam",
  },
  AL54652: {
    associateName: "Mohammed Siraj U",
    function: "PCM",
    teamLead: "Jugnu Varshney",
    functionalLeader: "Chatterjee, Anupam",
  },
  AL55434: {
    associateName: "Siddanagouda Naganagouda Patil",
    function: "PCM",
    teamLead: "Jugnu Varshney",
    functionalLeader: "Chatterjee, Anupam",
  },
  AH40739: {
    associateName: "Akkihal, Anmol Suresh",
    function: "PCM",
    teamLead: "Jugnu Varshney",
    functionalLeader: "Chatterjee, Anupam",
  },
  AL54657: {
    associateName: "Vyshak B ",
    function: "PCM",
    teamLead: "Jugnu Varshney",
    functionalLeader: "Chatterjee, Anupam",
  },
  AL55336: {
    associateName: "CHARKA, SRAVANI",
    function: "PCM",
    teamLead: "Jugnu Varshney",
    functionalLeader: "Chatterjee, Anupam",
  },
  AH54921: {
    associateName: "Komal Rani Srivastav",
    function: "PCM",
    teamLead: "Jugnu Varshney",
    functionalLeader: "Chatterjee, Anupam",
  },
  AH67875: {
    associateName: "Dinkar Kumar Singh",
    function: "PCM",
    teamLead: "Jugnu Varshney",
    functionalLeader: "Chatterjee, Anupam",
  },
  AM02771: {
    associateName: "Subash Chandra Maurya ",
    function: "PCM",
    teamLead: "Jugnu Varshney",
    functionalLeader: "Chatterjee, Anupam",
  },
  AM07834: {
    associateName: "Rahul Bisht",
    function: "PCM",
    teamLead: "Jugnu Varshney",
    functionalLeader: "Chatterjee, Anupam",
  },
  AF68742: {
    associateName: "Leena Vij",
    function: "PCM",
    teamLead: "Jugnu Varshney",
    functionalLeader: "Chatterjee, Anupam",
  },
  AL52344: {
    associateName: "M, Pradeep",
    function: "Re-work",
    teamLead: "K v s, Deepa",
    functionalLeader: "K v s, Deepa",
  },
  AL57743: {
    associateName: "Thami, Rajendra Kumar",
    function: "Re-work",
    teamLead: "K v s, Deepa",
    functionalLeader: "K v s, Deepa",
  },
  AG62600: {
    associateName: "Y N, Ananda",
    function: "Rosters",
    teamLead: "K v s, Deepa",
    functionalLeader: "K v s, Deepa",
  },
  AL66127: {
    associateName: "Chava, Kiran Kumar",
    function: "Rosters",
    teamLead: "K v s, Deepa",
    functionalLeader: "K v s, Deepa",
  },
  AH21746: {
    associateName: "Govardhan, Chavala",
    function: "Rosters",
    teamLead: "K v s, Deepa",
    functionalLeader: "K v s, Deepa",
  },
  AH76317: {
    associateName: "A, Samreen",
    function: "Rosters",
    teamLead: "K v s, Deepa",
    functionalLeader: "K v s, Deepa",
  },
  AL49287: {
    associateName: "Murthy, Ganesh (ganesh)",
    function: "Re-work",
    teamLead: "K v s, Deepa",
    functionalLeader: "K v s, Deepa",
  },
  AG98916: {
    associateName: "P, Sandhya",
    function: "L&D Offshore",
    teamLead: "K v s, Deepa",
    functionalLeader: "Kandasamy, Krishnakumar",
  },
  AH55675: {
    associateName: "Syam Prasad Reddy Chinthala",
    function: "PCM",
    teamLead: "Krishna, Karra Mohan",
    functionalLeader: "Chatterjee, Anupam",
  },
  AG99000: {
    associateName: "K, Bhuvaneshwari",
    function: "Provider Enrollment",
    teamLead: "Kumar, Nirmal",
    functionalLeader: "Chatterjee, Anupam",
  },
  AL56414: {
    associateName: "KARIBHIMAGOL, BHAKTI",
    function: "Provider Enrollment",
    teamLead: "Kumar, Nirmal",
    functionalLeader: "Chatterjee, Anupam",
  },
  AL55571: {
    associateName: "Betageri, Amruta M",
    function: "Provider Enrollment",
    teamLead: "Kumar, Nirmal",
    functionalLeader: "Chatterjee, Anupam",
  },
  AL53536: {
    associateName: "C, Kiran",
    function: "Provider Enrollment",
    teamLead: "Kumar, Nirmal",
    functionalLeader: "Chatterjee, Anupam",
  },
  AL53316: {
    associateName: "V, Karthik",
    function: "Provider Enrollment",
    teamLead: "Kumar, Nirmal",
    functionalLeader: "Chatterjee, Anupam",
  },
  AL53451: {
    associateName: "M, Meghana",
    function: "Provider Enrollment",
    teamLead: "Kumar, Nirmal",
    functionalLeader: "Chatterjee, Anupam",
  },
  AL53456: {
    associateName: "S P, Mythri",
    function: "Provider Enrollment",
    teamLead: "Kumar, Nirmal",
    functionalLeader: "Chatterjee, Anupam",
  },
  AL44127: {
    associateName: "Moger, Kumar",
    function: "Provider Enrollment",
    teamLead: "Kumar, Nirmal",
    functionalLeader: "Chatterjee, Anupam",
  },
  AL43472: {
    associateName: "B, Veena",
    function: "Provider Enrollment",
    teamLead: "Kumar, Nirmal",
    functionalLeader: "Chatterjee, Anupam",
  },
  AL48335: {
    associateName: "V, Manohara",
    function: "Provider Enrollment",
    teamLead: "Kumar, Nirmal",
    functionalLeader: "Chatterjee, Anupam",
  },
  AH55191: {
    associateName: "Mangalampalli, Sri Charan Sharma",
    function: "Provider Enrollment",
    teamLead: "Kumar, Nirmal",
    functionalLeader: "Chatterjee, Anupam",
  },
  AH84953: {
    associateName: "A U, Gangamma",
    function: "Provider Enrollment",
    teamLead: "Kumar, Nirmal",
    functionalLeader: "Chatterjee, Anupam",
  },
  AH85032: {
    associateName: "M, Tejashwee",
    function: "Provider Enrollment",
    teamLead: "Kumar, Nirmal",
    functionalLeader: "Chatterjee, Anupam",
  },
  AL43980: {
    associateName: "R, Bhavyashree",
    function: "Provider Enrollment",
    teamLead: "Kumar, Nirmal",
    functionalLeader: "Chatterjee, Anupam",
  },
  AL45921: {
    associateName: "SANKANGOUDRA, REKHA",
    function: "Provider Enrollment",
    teamLead: "Kumar, Nirmal",
    functionalLeader: "Chatterjee, Anupam",
  },
  AL43958: {
    associateName: "K S, Anjali",
    function: "Provider Enrollment",
    teamLead: "Kumar, Nirmal",
    functionalLeader: "K v s, Deepa",
  },
  AL53887: {
    associateName: "Barki, Gurunath",
    function: "Provider Enrollment",
    teamLead: "Kumar, Nirmal",
    functionalLeader: "K v s, Deepa",
  },
  AL53884: {
    associateName: "Dominic, Francis",
    function: "Provider Enrollment",
    teamLead: "Kumar, Nirmal",
    functionalLeader: "K v s, Deepa",
  },
  AL53475: {
    associateName: "Upadhye, Pushpadant",
    function: "Provider Enrollment",
    teamLead: "Kumar, Nirmal",
    functionalLeader: "K v s, Deepa",
  },
  AL42313: {
    associateName: "D'Souza, Dayana",
    function: "Provider Enrollment",
    teamLead: "Kumar, Nirmal",
    functionalLeader: "K v s, Deepa",
  },
  AH55238: {
    associateName: "Gadam Setty, Manasa",
    function: "Provider Enrollment",
    teamLead: "Kumar, Nirmal",
    functionalLeader: "K v s, Deepa",
  },
  AH76336: {
    associateName: "S N, Naidile",
    function: "Provider Enrollment",
    teamLead: "Kumar, Nirmal",
    functionalLeader: "K v s, Deepa",
  },
  AH76322: {
    associateName: "P S, Rohith",
    function: "Provider Enrollment",
    teamLead: "Kumar, Nirmal",
    functionalLeader: "K v s, Deepa",
  },
  AL52043: {
    associateName: "BS, Chethan",
    function: "Provider Enrollment",
    teamLead: "Kumar, Nirmal",
    functionalLeader: "K v s, Deepa",
  },
  AL55427: {
    associateName: "Maneypally, Pooja Sri",
    function: "Rosters",
    teamLead: "Laxmi Vandana, Sunkara",
    functionalLeader: "Muralidharan, TamilEnian",
  },
  AL53831: {
    associateName: "Nikhil Kumar, Molugu",
    function: "Rosters",
    teamLead: "Laxmi Vandana, Sunkara",
    functionalLeader: "Muralidharan, TamilEnian",
  },
  AL54488: {
    associateName: "Reddy, Palla Sampath",
    function: "Rosters",
    teamLead: "Laxmi Vandana, Sunkara",
    functionalLeader: "Muralidharan, TamilEnian",
  },
  AH54931: {
    associateName: "Mocherla Sai, Manasa Keertana",
    function: "Rosters",
    teamLead: "Laxmi Vandana, Sunkara",
    functionalLeader: "Muralidharan, TamilEnian",
  },
  AH55268: {
    associateName: "Josthna, Sindhu",
    function: "Rosters",
    teamLead: "Laxmi Vandana, Sunkara",
    functionalLeader: "Muralidharan, TamilEnian",
  },
  AH76355: {
    associateName: "Manasa, Bandari",
    function: "Rosters",
    teamLead: "Laxmi Vandana, Sunkara",
    functionalLeader: "Muralidharan, TamilEnian",
  },
  AH54952: {
    associateName: "Rajesh, Oruganti",
    function: "Rosters",
    teamLead: "Laxmi Vandana, Sunkara",
    functionalLeader: "Muralidharan, TamilEnian",
  },
  AL43270: {
    associateName: "Harshitha, Rayankula",
    function: "Rosters",
    teamLead: "Laxmi Vandana, Sunkara",
    functionalLeader: "Muralidharan, TamilEnian",
  },
  AL42305: {
    associateName: "Nikitha Kumari, Poplaith",
    function: "Rosters",
    teamLead: "Laxmi Vandana, Sunkara",
    functionalLeader: "Muralidharan, TamilEnian",
  },
  AL43985: {
    associateName: "Sarfaraz Khan, Sarfaraz (Sarfaraz Khan Sarfaraz Khan)",
    function: "Rosters",
    teamLead: "Laxmi Vandana, Sunkara",
    functionalLeader: "Muralidharan, TamilEnian",
  },
  AL43282: {
    associateName: "Sharma, Mahesh (Mahesh Sharma Mahesh Sharma)",
    function: "Rosters",
    teamLead: "Laxmi Vandana, Sunkara",
    functionalLeader: "Muralidharan, TamilEnian",
  },
  AL43168: {
    associateName: "Shatipallakollu, Tarun",
    function: "Rosters",
    teamLead: "Laxmi Vandana, Sunkara",
    functionalLeader: "Muralidharan, TamilEnian",
  },
  AG84921: {
    associateName: "S, Dinesh Kumar",
    function: "Rosters",
    teamLead: "Laxmi Vandana, Sunkara",
    functionalLeader: "Muralidharan, TamilEnian",
  },
  AL45036: {
    associateName: "M, Naveen",
    function: "Rosters",
    teamLead: "Laxmi Vandana, Sunkara",
    functionalLeader: "Muralidharan, TamilEnian",
  },
  AL53043: {
    associateName: "Kantati, Rajesh",
    function: "Rosters",
    teamLead: "Laxmi Vandana, Sunkara",
    functionalLeader: "Muralidharan, TamilEnian",
  },
  AL53594: {
    associateName: "Kavitha, Motti",
    function: "Rosters",
    teamLead: "Laxmi Vandana, Sunkara",
    functionalLeader: "Muralidharan, TamilEnian",
  },
  AL53587: {
    associateName: "KHIZARUDDIN, SHAIK",
    function: "Rosters",
    teamLead: "Laxmi Vandana, Sunkara",
    functionalLeader: "Muralidharan, TamilEnian",
  },
  AL53041: {
    associateName: "Preethi, Avishetty",
    function: "Rosters",
    teamLead: "Laxmi Vandana, Sunkara",
    functionalLeader: "Muralidharan, TamilEnian",
  },
  AL55414: {
    associateName: "Katkuri, Mahadev",
    function: "Rosters",
    teamLead: "Laxmi Vandana, Sunkara",
    functionalLeader: "Muralidharan, TamilEnian",
  },
  AL55413: {
    associateName: "Kodam, Manish Kumar",
    function: "Rosters",
    teamLead: "Laxmi Vandana, Sunkara",
    functionalLeader: "Muralidharan, TamilEnian",
  },
  AL55408: {
    associateName: "Nikhilkumar, Surbiryala",
    function: "Rosters",
    teamLead: "Laxmi Vandana, Sunkara",
    functionalLeader: "Muralidharan, TamilEnian",
  },
  AL55406: {
    associateName: "P, Sharanya",
    function: "Rosters",
    teamLead: "Laxmi Vandana, Sunkara",
    functionalLeader: "Muralidharan, TamilEnian",
  },
  AL54482: {
    associateName: "Panduranga, Seelamsetti Hiranya",
    function: "Rosters",
    teamLead: "Laxmi Vandana, Sunkara",
    functionalLeader: "Muralidharan, TamilEnian",
  },
  AL54648: {
    associateName: "Ramidi, Navakishore Reddy",
    function: "Rosters",
    teamLead: "Laxmi Vandana, Sunkara",
    functionalLeader: "Muralidharan, TamilEnian",
  },
  AL55327: {
    associateName: "SANDEEPKUMAR, MALLIPATEL",
    function: "Rosters",
    teamLead: "Laxmi Vandana, Sunkara",
    functionalLeader: "Muralidharan, TamilEnian",
  },
  AH22010: {
    associateName: "Rashi, Karnati Naga",
    function: "Rosters",
    teamLead: "Laxmi Vandana, Sunkara",
    functionalLeader: "Muralidharan, TamilEnian",
  },
  AL46049: {
    associateName: "Ruchitha, Bomma",
    function: "Re-work",
    teamLead: "M, Pradeep",
    functionalLeader: "K v s, Deepa",
  },
  AL53827: {
    associateName: "Kumar P, Krithik",
    function: "Re-work",
    teamLead: "M, Pradeep",
    functionalLeader: "K v s, Deepa",
  },
  AL43977: {
    associateName: "Poojari, Rithin Prakash",
    function: "Re-work",
    teamLead: "M, Pradeep",
    functionalLeader: "K v s, Deepa",
  },
  AL53526: {
    associateName: "A, Poorvaja",
    function: "Re-work",
    teamLead: "M, Pradeep",
    functionalLeader: "K v s, Deepa",
  },
  AL53539: {
    associateName: "Khanai, Amruta (Khanai Amruta)",
    function: "Re-work",
    teamLead: "M, Pradeep",
    functionalLeader: "K v s, Deepa",
  },
  AL53590: {
    associateName: "Poornima, Kannehalligowdra",
    function: "Re-work",
    teamLead: "M, Pradeep",
    functionalLeader: "K v s, Deepa",
  },
  AL53538: {
    associateName: "R, Harshitha",
    function: "Re-work",
    teamLead: "M, Pradeep",
    functionalLeader: "K v s, Deepa",
  },
  AL43262: {
    associateName: "Saunshi, Mahesh",
    function: "Re-work",
    teamLead: "M, Pradeep",
    functionalLeader: "K v s, Deepa",
  },
  AL43982: {
    associateName: "J, Shobha",
    function: "Re-work",
    teamLead: "M, Pradeep",
    functionalLeader: "K v s, Deepa",
  },
  AG54750: {
    associateName: "Chandana, M",
    function: "Re-work",
    teamLead: "M, Pradeep",
    functionalLeader: "K v s, Deepa",
  },
  AL53455: {
    associateName: "shiragoor, Monika",
    function: "Re-work",
    teamLead: "M, Pradeep",
    functionalLeader: "K v s, Deepa",
  },
  AG98935: {
    associateName: "S, Divya",
    function: "Re-work",
    teamLead: "M, Pradeep",
    functionalLeader: "K v s, Deepa",
  },
  AL56463: {
    associateName: "H B, Tejaswini",
    function: "Re-work",
    teamLead: "M, Pradeep",
    functionalLeader: "K v s, Deepa",
  },
  AL48124: {
    associateName: "Gorla, Abraham Lincoln",
    function: "L&D Offshore",
    teamLead: "Machannagari, Jaipal Reddy",
    functionalLeader: "Kandasamy, Krishnakumar",
  },
  AG98901: {
    associateName: "Kp, Prageesh",
    function: "L&D Offshore",
    teamLead: "Machannagari, Jaipal Reddy",
    functionalLeader: "Kandasamy, Krishnakumar",
  },
  AL42992: {
    associateName: "S, SUMANTH",
    function: "Rosters",
    teamLead: "Machannagari, Jaipal Reddy",
    functionalLeader: "Muralidharan, TamilEnian",
  },
  AG26245: {
    associateName: "Kumar R, Kishor",
    function: "Rosters",
    teamLead: "Machannagari, Jaipal Reddy",
    functionalLeader: "Muralidharan, TamilEnian",
  },
  AG66094: {
    associateName: "Madani, Mohammed",
    function: "Rosters",
    teamLead: "Machannagari, Jaipal Reddy",
    functionalLeader: "Muralidharan, TamilEnian",
  },
  AG54727: {
    associateName: "S N, Sindhu",
    function: "Rosters",
    teamLead: "Machannagari, Jaipal Reddy",
    functionalLeader: "Muralidharan, TamilEnian",
  },
  AH55222: {
    associateName: "Rahul, Emmidyshetty",
    function: "Rosters",
    teamLead: "Machannagari, Jaipal Reddy",
    functionalLeader: "Muralidharan, TamilEnian",
  },
  AG24670: {
    associateName: "Raj, Vikram",
    function: "Rosters",
    teamLead: "Muralidharan, TamilEnian",
    functionalLeader: "Muralidharan, TamilEnian",
  },
  AL52636: {
    associateName: "Biraiah, DEEPAK",
    function: "Rosters",
    teamLead: "Muralidharan, TamilEnian",
    functionalLeader: "Muralidharan, TamilEnian",
  },
  AL57101: {
    associateName: "Laxmi Vandana, Sunkara",
    function: "Rosters",
    teamLead: "Muralidharan, TamilEnian",
    functionalLeader: "Muralidharan, TamilEnian",
  },
  AL50030: {
    associateName: "Ranganathan, Sharmila Devi",
    function: "Rosters",
    teamLead: "Muralidharan, TamilEnian",
    functionalLeader: "Muralidharan, TamilEnian",
  },
  AL47537: {
    associateName: "Aruchamy, Karuppusamy",
    function: "Rosters",
    teamLead: "Muralidharan, TamilEnian",
    functionalLeader: "Muralidharan, TamilEnian",
  },
  AG54455: {
    associateName: "Machannagari, Jaipal Reddy",
    function: "Rosters",
    teamLead: "Muralidharan, TamilEnian",
    functionalLeader: "Muralidharan, TamilEnian",
  },
  AL50044: {
    associateName: ", Asha",
    function: "Rosters",
    teamLead: "Muralidharan, TamilEnian",
    functionalLeader: "Muralidharan, TamilEnian",
  },
  AL47104: {
    associateName: "Balu, Prakash",
    function: "Rosters",
    teamLead: "Muralidharan, TamilEnian",
    functionalLeader: "Muralidharan, TamilEnian",
  },
  AH47129: {
    associateName: "Mahapatra, Susmita",
    function: "Rosters",
    teamLead: "Muralidharan, TamilEnian",
    functionalLeader: "Muralidharan, TamilEnian",
  },
  AL69191: {
    associateName: "Munjal, Himani",
    function: "PCM",
    teamLead: "Pathak, Anupam",
    functionalLeader: "Chatterjee, Anupam",
  },
  AL67623: {
    associateName: "Sharma, Drishti",
    function: "PCM",
    teamLead: "Pathak, Anupam",
    functionalLeader: "Chatterjee, Anupam",
  },
  AL67622: {
    associateName: "Khushboo, Kumari",
    function: "PCM",
    teamLead: "Pathak, Anupam",
    functionalLeader: "Chatterjee, Anupam",
  },
  AL67616: {
    associateName: "Yadav, Neha",
    function: "PCM",
    teamLead: "Pathak, Anupam",
    functionalLeader: "Chatterjee, Anupam",
  },
  AL66171: {
    associateName: "Mishra, Pragya",
    function: "PCM",
    teamLead: "Pathak, Anupam",
    functionalLeader: "Chatterjee, Anupam",
  },
  AL66115: {
    associateName: "Anjana",
    function: "PCM",
    teamLead: "Pathak, Anupam",
    functionalLeader: "Chatterjee, Anupam",
  },
  AL64975: {
    associateName: "Bajpai, Avantika",
    function: "PCM",
    teamLead: "Pathak, Anupam",
    functionalLeader: "Chatterjee, Anupam",
  },
  AL64518: {
    associateName: "Asif Iqbal",
    function: "PCM",
    teamLead: "Pathak, Anupam",
    functionalLeader: "Chatterjee, Anupam",
  },
  AL60711: {
    associateName: "Chouvhan Deepesh Mohan",
    function: "PCM",
    teamLead: "Pathak, Anupam",
    functionalLeader: "Chatterjee, Anupam",
  },
  AL59745: {
    associateName: "Samyak Jain",
    function: "PCM",
    teamLead: "Pathak, Anupam",
    functionalLeader: "Chatterjee, Anupam",
  },
  AL64187: {
    associateName: "kumari, Sapna",
    function: "PCM",
    teamLead: "Pathak, Anupam",
    functionalLeader: "Chatterjee, Anupam",
  },
  AL60050: {
    associateName: "Mishra, Ankesh",
    function: "PCM",
    teamLead: "Pathak, Anupam",
    functionalLeader: "Chatterjee, Anupam",
  },
  AL60256: {
    associateName: "Negi, Himanshi",
    function: "PCM",
    teamLead: "Pathak, Anupam",
    functionalLeader: "Chatterjee, Anupam",
  },
  AL64356: {
    associateName: "Sharma, Manmohan",
    function: "PCM",
    teamLead: "Pathak, Anupam",
    functionalLeader: "Chatterjee, Anupam",
  },
  AL60267: {
    associateName: "Tetri, Kunal",
    function: "PCM",
    teamLead: "Pathak, Anupam",
    functionalLeader: "Chatterjee, Anupam",
  },
  AL66209: {
    associateName: "Verma, Rupali",
    function: "PCM",
    teamLead: "Pathak, Anupam",
    functionalLeader: "Chatterjee, Anupam",
  },
  AH54985: {
    associateName: "Avinash, Gandala",
    function: "PCM",
    teamLead: "Rajani, Radhae",
    functionalLeader: "Chatterjee, Anupam",
  },
  AL54475: {
    associateName: "Bhaskari, Girish",
    function: "PCM",
    teamLead: "Rajani, Radhae",
    functionalLeader: "Chatterjee, Anupam",
  },
  AL52950: {
    associateName: "R, Dhanusha",
    function: "PCM",
    teamLead: "Rajani, Radhae",
    functionalLeader: "Chatterjee, Anupam",
  },
  AH21968: {
    associateName: "Yadav, Priyanka",
    function: "PCM",
    teamLead: "Rajani, Radhae",
    functionalLeader: "Chatterjee, Anupam",
  },
  AH76319: {
    associateName: "K A, Ashwini",
    function: "PCM",
    teamLead: "Rajani, Radhae",
    functionalLeader: "Chatterjee, Anupam",
  },
  AH90434: {
    associateName: "Mohsin, Mohammed",
    function: "PCM",
    teamLead: "Rajani, Radhae",
    functionalLeader: "Chatterjee, Anupam",
  },
  AH72512: {
    associateName: "Pinnitti, Manasa Reddy",
    function: "PCM",
    teamLead: "Rajani, Radhae",
    functionalLeader: "Chatterjee, Anupam",
  },
  AL53823: {
    associateName: "Quadri, Syed",
    function: "PCM",
    teamLead: "Rajani, Radhae",
    functionalLeader: "Chatterjee, Anupam",
  },
  AL46562: {
    associateName: "M, Backiyalakshmi",
    function: "PCM",
    teamLead: "Rajani, Radhae",
    functionalLeader: "Chatterjee, Anupam",
  },
  AL43356: {
    associateName: "Madithati, Ashritha",
    function: "PCM",
    teamLead: "Rajani, Radhae",
    functionalLeader: "Chatterjee, Anupam",
  },
  AH55197: {
    associateName: "Neernemula, Jhansi",
    function: "PCM",
    teamLead: "Rajani, Radhae",
    functionalLeader: "Chatterjee, Anupam",
  },
  AL53785: {
    associateName: "Poorna Chandra, Perugu",
    function: "PCM",
    teamLead: "Rajani, Radhae",
    functionalLeader: "Chatterjee, Anupam",
  },
  AL55576: {
    associateName: "SAI KUMAR, MEDIBOYINA",
    function: "PCM",
    teamLead: "Rajani, Radhae",
    functionalLeader: "Chatterjee, Anupam",
  },
  AL53314: {
    associateName: "THADISHETTI, PUNEETHA",
    function: "PCM",
    teamLead: "Rajani, Radhae",
    functionalLeader: "Chatterjee, Anupam",
  },
  AL64358: {
    associateName: "Himanshu Kumar",
    function: "PCM",
    teamLead: "Rajani, Radhae",
    functionalLeader: "Chatterjee, Anupam",
  },
  AL64367: {
    associateName: "Vishal Sharma",
    function: "PCM",
    teamLead: "Rajani, Radhae",
    functionalLeader: "Chatterjee, Anupam",
  },
  AH54937: {
    associateName: "Pindi, Mahitha",
    function: "PCM",
    teamLead: "Rajani, Radhae",
    functionalLeader: "Chatterjee, Anupam",
  },
  AL53630: {
    associateName: "Shaik, Kamaluddin",
    function: "PCM",
    teamLead: "Rajani, Radhae",
    functionalLeader: "Chatterjee, Anupam",
  },
  AL55369: {
    associateName: "Likitha, Nemuri",
    function: "PCM",
    teamLead: "Rajani, Radhae",
    functionalLeader: "Chatterjee, Anupam",
  },
  AH54997: {
    associateName: "Mandha, Ashwini",
    function: "PCM",
    teamLead: "Rajani, Radhae",
    functionalLeader: "Chatterjee, Anupam",
  },
  AG84917: {
    associateName: "Sravani Kampati",
    function: "PCM",
    teamLead: "Rajani, Radhae",
    functionalLeader: "Chatterjee, Anupam",
  },
  AG54429: {
    associateName: "Barik, Jyotirmayee",
    function: "PCM",
    teamLead: "Rajani, Radhae",
    functionalLeader: "Chatterjee, Anupam",
  },
  AL53540: {
    associateName: "H, NANDINI",
    function: "DDO",
    teamLead: "Ramakrishna Bhat, Anuradha ",
    functionalLeader: "Ravindran, Arun Raj",
  },
  AL53015: {
    associateName: "K N, Ranjitha",
    function: "DDO",
    teamLead: "Ramakrishna Bhat, Anuradha ",
    functionalLeader: "Ravindran, Arun Raj",
  },
  AL52954: {
    associateName: "R, Mahesh",
    function: "DDO",
    teamLead: "Ramakrishna Bhat, Anuradha ",
    functionalLeader: "Ravindran, Arun Raj",
  },
  AL53035: {
    associateName: "S L, MEGHANA",
    function: "DDO",
    teamLead: "Ramakrishna Bhat, Anuradha ",
    functionalLeader: "Ravindran, Arun Raj",
  },
  AH78844: {
    associateName: "B, Pavithra",
    function: "DDO",
    teamLead: "Ramakrishna Bhat, Anuradha ",
    functionalLeader: "Ravindran, Arun Raj",
  },
  AG54755: {
    associateName: "Dcosta, Joseph",
    function: "DDO",
    teamLead: "Ramakrishna Bhat, Anuradha ",
    functionalLeader: "Ravindran, Arun Raj",
  },
  AL43291: {
    associateName: "Naik, Jyoti Somayya (Jyoti)",
    function: "DDO",
    teamLead: "Ramakrishna Bhat, Anuradha ",
    functionalLeader: "Ravindran, Arun Raj",
  },
  AL50727: {
    associateName: "Manokaran, Krishnamoorthi",
    function: "DDO",
    teamLead: "Ramakrishna Bhat, Anuradha ",
    functionalLeader: "Ravindran, Arun Raj",
  },
  AL53476: {
    associateName: "Pujari, Vitthal Kallappa",
    function: "DDO",
    teamLead: "Ramakrishna Bhat, Anuradha ",
    functionalLeader: "Ravindran, Arun Raj",
  },
  AL42990: {
    associateName: "L, Preethi",
    function: "DDO",
    teamLead: "Ramakrishna Bhat, Anuradha ",
    functionalLeader: "Ravindran, Arun Raj",
  },
  AL43353: {
    associateName: "Shetty, C Harshitha",
    function: "DDO",
    teamLead: "Ramakrishna Bhat, Anuradha ",
    functionalLeader: "Ravindran, Arun Raj",
  },
  AL43960: {
    associateName: "G M, Gayithri",
    function: "DDO",
    teamLead: "Ramakrishna Bhat, Anuradha ",
    functionalLeader: "Ravindran, Arun Raj",
  },
  AL42988: {
    associateName: "Bagwale, Ubedulla",
    function: "DDO",
    teamLead: "Ramakrishna Bhat, Anuradha ",
    functionalLeader: "Ravindran, Arun Raj",
  },
  AL43362: {
    associateName: "Balikai, Sapna",
    function: "DDO",
    teamLead: "Ramakrishna Bhat, Anuradha ",
    functionalLeader: "Ravindran, Arun Raj",
  },
  AL56362: {
    associateName: "M, SUSHMA",
    function: "DDO",
    teamLead: "Ramakrishna Bhat, Anuradha ",
    functionalLeader: "Ravindran, Arun Raj",
  },
  AL56217: {
    associateName: "G H, Sunand kumar",
    function: "DDO",
    teamLead: "Ramakrishna Bhat, Anuradha ",
    functionalLeader: "Ravindran, Arun Raj",
  },
  AL47206: {
    associateName: "M K, Thanuja",
    function: "DDO",
    teamLead: "Ramakrishna Bhat, Anuradha ",
    functionalLeader: "Ravindran, Arun Raj",
  },
  AL42996: {
    associateName: "Samaje, Suhasini",
    function: "DDO",
    teamLead: "Ramakrishna Bhat, Anuradha ",
    functionalLeader: "Ravindran, Arun Raj",
  },
  AL43266: {
    associateName: "P S, Srushti",
    function: "DDO",
    teamLead: "Ramakrishna Bhat, Anuradha ",
    functionalLeader: "Ravindran, Arun Raj",
  },
  AL50728: {
    associateName: "Bilegodu, Gajendra",
    function: "DDO",
    teamLead: "Ramakrishna Bhat, Anuradha ",
    functionalLeader: "Ravindran, Arun Raj",
  },
  AG54731: {
    associateName: "S, Sabeeha",
    function: "Rosters",
    teamLead: "Ranganathan, Sharmila Devi",
    functionalLeader: "Muralidharan, TamilEnian",
  },
  AL43986: {
    associateName: "Pujeri, Suma (Pujeri Suma)",
    function: "Rosters",
    teamLead: "Ranganathan, Sharmila Devi",
    functionalLeader: "Muralidharan, TamilEnian",
  },
  AL55430: {
    associateName: "Bedkihale, Bhagyashri",
    function: "Rosters",
    teamLead: "Ranganathan, Sharmila Devi",
    functionalLeader: "Muralidharan, TamilEnian",
  },
  AL55404: {
    associateName: "CHANJAL, KK",
    function: "Rosters",
    teamLead: "Ranganathan, Sharmila Devi",
    functionalLeader: "Muralidharan, TamilEnian",
  },
  AL53815: {
    associateName: "M, Manoj",
    function: "Rosters",
    teamLead: "Ranganathan, Sharmila Devi",
    functionalLeader: "Muralidharan, TamilEnian",
  },
  AL52927: {
    associateName: "Supriya V, Maria",
    function: "Rosters",
    teamLead: "Ranganathan, Sharmila Devi",
    functionalLeader: "Muralidharan, TamilEnian",
  },
  AL53460: {
    associateName: "., Nagaraj",
    function: "Rosters",
    teamLead: "Ranganathan, Sharmila Devi",
    functionalLeader: "Muralidharan, TamilEnian",
  },
  AL55375: {
    associateName: "B V, SWETHA",
    function: "Rosters",
    teamLead: "Ranganathan, Sharmila Devi",
    functionalLeader: "Muralidharan, TamilEnian",
  },
  AL55428: {
    associateName: "HUSSAIN, MD SHAKIB",
    function: "Rosters",
    teamLead: "Ranganathan, Sharmila Devi",
    functionalLeader: "Muralidharan, TamilEnian",
  },
  AL43969: {
    associateName: "V, Varalakshmi",
    function: "Rosters",
    teamLead: "Ranganathan, Sharmila Devi",
    functionalLeader: "Muralidharan, TamilEnian",
  },
  AL53036: {
    associateName: "Narasimha, Harshitha.N",
    function: "Rosters",
    teamLead: "Ranganathan, Sharmila Devi",
    functionalLeader: "Muralidharan, TamilEnian",
  },
  AL53837: {
    associateName: "Katti, Pratiksha (Pratiksha S Katti)",
    function: "Rosters",
    teamLead: "Ranganathan, Sharmila Devi",
    functionalLeader: "Muralidharan, TamilEnian",
  },
  AL54322: {
    associateName: "S, Thangaraj",
    function: "Rosters",
    teamLead: "Ranganathan, Sharmila Devi",
    functionalLeader: "Muralidharan, TamilEnian",
  },
  AL82684: {
    associateName: "Suhail, Ahamed",
    function: "Rosters",
    teamLead: "Ranganathan, Sharmila Devi",
    functionalLeader: "Muralidharan, TamilEnian",
  },
  AL43966: {
    associateName: "Walaki, Nakushav Raju",
    function: "Rosters",
    teamLead: "Ranganathan, Sharmila Devi",
    functionalLeader: "Muralidharan, TamilEnian",
  },
  AL53534: {
    associateName: "Arikatti, Sujata (Arikatti Sujata Arikatti)",
    function: "Rosters",
    teamLead: "Ranganathan, Sharmila Devi",
    functionalLeader: "Muralidharan, TamilEnian",
  },
  AL53307: {
    associateName: "T M, Ashwini",
    function: "Rosters",
    teamLead: "Ranganathan, Sharmila Devi",
    functionalLeader: "Muralidharan, TamilEnian",
  },
  AL33072: {
    associateName: "Annamalai, Anishkumar",
    function: "Rosters",
    teamLead: "Ranganathan, Sharmila Devi",
    functionalLeader: "Muralidharan, TamilEnian",
  },
  AH72509: {
    associateName: "K C, Navya",
    function: "Rosters",
    teamLead: "Ranganathan, Sharmila Devi",
    functionalLeader: "Muralidharan, TamilEnian",
  },
  AL48788: {
    associateName: "Mohammed, Ather",
    function: "L&D Offshore",
    teamLead: "Ravindran, Arun Raj",
    functionalLeader: "Kandasamy, Krishnakumar",
  },
  AL48126: {
    associateName: "Bhutani, Srikant",
    function: "L&D Offshore",
    teamLead: "Ravindran, Arun Raj",
    functionalLeader: "Kandasamy, Krishnakumar",
  },
  AG62603: {
    associateName: "Ramakrishna Bhat, Anuradha",
    function: "DDO",
    teamLead: "Ravindran, Arun Raj",
    functionalLeader: "Ravindran, Arun Raj",
  },
  AG61765: {
    associateName: "Nalli, Tirupathi",
    function: "DDO",
    teamLead: "Ravindran, Arun Raj",
    functionalLeader: "Ravindran, Arun Raj",
  },
  AL59260: {
    associateName: "Verma, Aryan",
    function: "DDO",
    teamLead: "Ravindran, Arun Raj",
    functionalLeader: "Ravindran, Arun Raj",
  },
  AL52345: {
    associateName: "Samuel, Sonu",
    function: "DDO",
    teamLead: "Ravindran, Arun Raj",
    functionalLeader: "Ravindran, Arun Raj",
  },
  AH21760: {
    associateName: "D, Ganga",
    function: "DDO",
    teamLead: "Ravindran, Arun Raj",
    functionalLeader: "Ravindran, Arun Raj",
  },
  AG62894: {
    associateName: "A, Manjunath",
    function: "DDO",
    teamLead: "Ravindran, Arun Raj",
    functionalLeader: "Ravindran, Arun Raj",
  },
  AL60655: {
    associateName: "Saxena, Sangam",
    function: "DDO",
    teamLead: "Ravindran, Arun Raj",
    functionalLeader: "Ravindran, Arun Raj",
  },
  AL59258: {
    associateName: "Adhikary, Gopa",
    function: "DDO",
    teamLead: "Ravindran, Arun Raj",
    functionalLeader: "Ravindran, Arun Raj",
  },
  AG54737: {
    associateName: "K, Sahithya",
    function: "DDO",
    teamLead: "Samuel, Sonu",
    functionalLeader: "Ravindran, Arun Raj",
  },
  AL43974: {
    associateName: "A H, Ashwini",
    function: "DDO",
    teamLead: "Samuel, Sonu",
    functionalLeader: "Ravindran, Arun Raj",
  },
  AL53098: {
    associateName: "A, Gayathri",
    function: "DDO",
    teamLead: "Samuel, Sonu",
    functionalLeader: "Ravindran, Arun Raj",
  },
  AL43352: {
    associateName: "CN, Divya",
    function: "DDO",
    teamLead: "Samuel, Sonu",
    functionalLeader: "Ravindran, Arun Raj",
  },
  AL52956: {
    associateName: "Gajannavar, Mantesh",
    function: "DDO",
    teamLead: "Samuel, Sonu",
    functionalLeader: "Ravindran, Arun Raj",
  },
  AL43983: {
    associateName: "Kannan, Gokul",
    function: "DDO",
    teamLead: "Samuel, Sonu",
    functionalLeader: "Ravindran, Arun Raj",
  },
  AL54480: {
    associateName: "M, Varun",
    function: "DDO",
    teamLead: "Samuel, Sonu",
    functionalLeader: "Ravindran, Arun Raj",
  },
  AL54057: {
    associateName: "Naresh Kumar, Bhoomika",
    function: "DDO",
    teamLead: "Samuel, Sonu",
    functionalLeader: "Ravindran, Arun Raj",
  },
  AL79031: {
    associateName: "M, Dilli Babu",
    function: "DDO",
    teamLead: "Samuel, Sonu",
    functionalLeader: "Ravindran, Arun Raj",
  },
  AL43361: {
    associateName: "R, Karthik",
    function: "DDO",
    teamLead: "Samuel, Sonu",
    functionalLeader: "Ravindran, Arun Raj",
  },
  AL43984: {
    associateName: "DJ, Harsha",
    function: "DDO",
    teamLead: "Samuel, Sonu",
    functionalLeader: "Ravindran, Arun Raj",
  },
  AL55426: {
    associateName: "HARIVELAM GANAPPAGARI, UPENDRA",
    function: "DDO",
    teamLead: "Samuel, Sonu",
    functionalLeader: "Ravindran, Arun Raj",
  },
  AL53457: {
    associateName: "N, SPOORTHI",
    function: "DDO",
    teamLead: "Samuel, Sonu",
    functionalLeader: "Ravindran, Arun Raj",
  },
  AL53537: {
    associateName: "R, Geetha",
    function: "DDO",
    teamLead: "Samuel, Sonu",
    functionalLeader: "Ravindran, Arun Raj",
  },
  AG99026: {
    associateName: "M, Shree Pooja",
    function: "DDO",
    teamLead: "Samuel, Sonu",
    functionalLeader: "Ravindran, Arun Raj",
  },
  AL43979: {
    associateName: "Patgar, Tejaswini Nagaraj",
    function: "DDO",
    teamLead: "Samuel, Sonu",
    functionalLeader: "Ravindran, Arun Raj",
  },
  AL43349: {
    associateName: "Reddy U, Narendra",
    function: "DDO",
    teamLead: "Samuel, Sonu",
    functionalLeader: "Ravindran, Arun Raj",
  },
  AL44126: {
    associateName: "H N, Meghana",
    function: "DDO",
    teamLead: "Samuel, Sonu",
    functionalLeader: "Ravindran, Arun Raj",
  },
  AG24666: {
    associateName: "Muniraj, Aishwarya",
    function: "DDO",
    teamLead: "Samuel, Sonu",
    functionalLeader: "Ravindran, Arun Raj",
  },
  AL43258: {
    associateName: "P, Shajan singh",
    function: "DDO",
    teamLead: "Samuel, Sonu",
    functionalLeader: "Ravindran, Arun Raj",
  },
  AG24639: {
    associateName: "M, Sumithra",
    function: "DDO",
    teamLead: "Samuel, Sonu",
    functionalLeader: "Ravindran, Arun Raj",
  },
  AL67618: {
    associateName: "Chauhan, Suruchi",
    function: "DDO",
    teamLead: "Saxena, Sangam",
    functionalLeader: "K v s, Deepa",
  },
  AL67696: {
    associateName: "Hooda, Meenu",
    function: "DDO",
    teamLead: "Saxena, Sangam",
    functionalLeader: "K v s, Deepa",
  },
  AL66293: {
    associateName: "Saigal, Sneha",
    function: "DDO",
    teamLead: "Saxena, Sangam",
    functionalLeader: "K v s, Deepa",
  },
  AL54663: {
    associateName: "Rizvi, Alisha",
    function: "DDO",
    teamLead: "Saxena, Sangam",
    functionalLeader: "Ravindran, Arun Raj",
  },
  AL67619: {
    associateName: "Kumari, Lovely",
    function: "DDO",
    teamLead: "Saxena, Sangam",
    functionalLeader: "Ravindran, Arun Raj",
  },
  AL64302: {
    associateName: "Bhatia, Somesh",
    function: "DDO",
    teamLead: "Saxena, Sangam",
    functionalLeader: "Ravindran, Arun Raj",
  },
  AL67302: {
    associateName: "Pandey, Nidhi",
    function: "DDO",
    teamLead: "Saxena, Sangam",
    functionalLeader: "Ravindran, Arun Raj",
  },
  AL59936: {
    associateName: "Malik, Aditya",
    function: "DDO",
    teamLead: "Saxena, Sangam",
    functionalLeader: "Ravindran, Arun Raj",
  },
  AL59255: {
    associateName: "kumar, Sachin",
    function: "DDO",
    teamLead: "Saxena, Sangam",
    functionalLeader: "Ravindran, Arun Raj",
  },
  AL64186: {
    associateName: "Mir, Asif",
    function: "DDO",
    teamLead: "Saxena, Sangam",
    functionalLeader: "Ravindran, Arun Raj",
  },
  AL67628: {
    associateName: "Malik, Konika",
    function: "DDO",
    teamLead: "Saxena, Sangam",
    functionalLeader: "Ravindran, Arun Raj",
  },
  AL60025: {
    associateName: "Sahi, Dhiraj Singh",
    function: "DDO",
    teamLead: "Saxena, Sangam",
    functionalLeader: "Ravindran, Arun Raj",
  },
  AL64559: {
    associateName: "Pandey, Anushka",
    function: "DDO",
    teamLead: "Saxena, Sangam",
    functionalLeader: "Ravindran, Arun Raj",
  },
  AL67299: {
    associateName: "Bajpai, Kamiksha",
    function: "DDO",
    teamLead: "Saxena, Sangam",
    functionalLeader: "Ravindran, Arun Raj",
  },
  AL66921: {
    associateName: "Kapoor, Sonali",
    function: "DDO",
    teamLead: "Saxena, Sangam",
    functionalLeader: "Ravindran, Arun Raj",
  },
  AL66208: {
    associateName: "Singh, Akanksha (Akanksha)",
    function: "DDO",
    teamLead: "Saxena, Sangam",
    functionalLeader: "Ravindran, Arun Raj",
  },
  AH55262: {
    associateName: "Keshan, Ambika",
    function: "DDO",
    teamLead: "Saxena, Sangam",
    functionalLeader: "Ravindran, Arun Raj",
  },
  AH33362: {
    associateName: "Jain, Harsh",
    function: "PCM",
    teamLead: "Subbarao Pokuri",
    functionalLeader: "Chatterjee, Anupam",
  },
  AL55577: {
    associateName: "Indraganti Reshmi Sastry ",
    function: "PCM",
    teamLead: "Subbarao Pokuri",
    functionalLeader: "Chatterjee, Anupam",
  },
  AL52454: {
    associateName: "C, KAVYA ",
    function: "PCM",
    teamLead: "Subbarao Pokuri",
    functionalLeader: "Chatterjee, Anupam",
  },
  AL53468: {
    associateName: "Prashandini, Manasa",
    function: "PCM",
    teamLead: "Subbarao Pokuri",
    functionalLeader: "Chatterjee, Anupam",
  },
  AL53530: {
    associateName: "VIDYA, R",
    function: "PCM",
    teamLead: "Subbarao Pokuri",
    functionalLeader: "Chatterjee, Anupam",
  },
  AL53472: {
    associateName: "PS, Poojashree",
    function: "PCM",
    teamLead: "Subbarao Pokuri",
    functionalLeader: "Chatterjee, Anupam",
  },
  AL51812: {
    associateName: "Nimbalkar, Sushma",
    function: "PCM",
    teamLead: "Subbarao Pokuri",
    functionalLeader: "Chatterjee, Anupam",
  },
  AL60048: {
    associateName: "Kasif Hussain",
    function: "PCM",
    teamLead: "Subbarao Pokuri",
    functionalLeader: "Chatterjee, Anupam",
  },
  AL64292: {
    associateName: "Jatin",
    function: "PCM",
    teamLead: "Subbarao Pokuri",
    functionalLeader: "Chatterjee, Anupam",
  },
  AL65312: {
    associateName: "Sakshi Tiwari",
    function: "PCM",
    teamLead: "Subbarao Pokuri",
    functionalLeader: "Chatterjee, Anupam",
  },
  AL66334: {
    associateName: "Harshita Srivastava",
    function: "PCM",
    teamLead: "Subbarao Pokuri",
    functionalLeader: "Chatterjee, Anupam",
  },
  AL67300: {
    associateName: "Lovely Sharma",
    function: "PCM",
    teamLead: "Subbarao Pokuri",
    functionalLeader: "Chatterjee, Anupam",
  },
  AL67757: {
    associateName: "Rechel Joy Mulpur",
    function: "PCM",
    teamLead: "Subbarao Pokuri",
    functionalLeader: "Chatterjee, Anupam",
  },
  AL55570: {
    associateName: "Vijay, Telukula",
    function: "PCM",
    teamLead: "Subbarao Pokuri",
    functionalLeader: "Chatterjee, Anupam",
  },
  AL64332: {
    associateName: "Radhika Gulati",
    function: "PCM",
    teamLead: "Subbarao Pokuri",
    functionalLeader: "Chatterjee, Anupam",
  },
  AL54661: {
    associateName: "B.S.Hema",
    function: "PCM",
    teamLead: "Subbarao Pokuri",
    functionalLeader: "Chatterjee, Anupam",
  },
  AH33410: {
    associateName: "Biswal, Jitendra Kumar",
    function: "PCM",
    teamLead: "Subbarao Pokuri",
    functionalLeader: "Chatterjee, Anupam",
  },
  AH21994: {
    associateName: "Lahari, Muskipeta Sindhu",
    function: "PCM",
    teamLead: "Subbarao Pokuri",
    functionalLeader: "Chatterjee, Anupam",
  },
  AG55929: {
    associateName: "Nikhitha Mangali",
    function: "PCM",
    teamLead: "Subbarao Pokuri",
    functionalLeader: "Chatterjee, Anupam",
  },
  AL65827: {
    associateName: "Sakshi Saigal",
    function: "PCM",
    teamLead: "Subbarao Pokuri",
    functionalLeader: "Chatterjee, Anupam",
  },
  AG98921: {
    associateName: "Domakuntla, Akhila",
    function: "PCM",
    teamLead: "Subbarao Pokuri",
    functionalLeader: "Chatterjee, Anupam",
  },
  AL46120: {
    associateName: "V, Vedavathi",
    function: "PCM",
    teamLead: "Subbarao Pokuri",
    functionalLeader: "Chatterjee, Anupam",
  },
  AH99364: {
    associateName: "Hussain, Raichur Mohammed",
    function: "Re-work",
    teamLead: "Thami, Rajendra Kumar",
    functionalLeader: "K v s, Deepa",
  },
  AL55423: {
    associateName: "Pedapati, Naveen Bala Prabhu",
    function: "Re-work",
    teamLead: "Thami, Rajendra Kumar",
    functionalLeader: "K v s, Deepa",
  },
  AL57280: {
    associateName: "Khan, Mohd Ashraf",
    function: "Re-work",
    teamLead: "Thami, Rajendra Kumar",
    functionalLeader: "K v s, Deepa",
  },
  AL42404: {
    associateName: "Vinay Babu, Grandala",
    function: "Re-work",
    teamLead: "Thami, Rajendra Kumar",
    functionalLeader: "K v s, Deepa",
  },
  AL53474: {
    associateName: "Bandaiahgari, ShasiKumar",
    function: "Re-work",
    teamLead: "Thami, Rajendra Kumar",
    functionalLeader: "K v s, Deepa",
  },
  AL53842: {
    associateName: "Satya Prakash, Kanakanuru",
    function: "Re-work",
    teamLead: "Thami, Rajendra Kumar",
    functionalLeader: "K v s, Deepa",
  },
  AL54484: {
    associateName: "M, Uday",
    function: "Re-work",
    teamLead: "Thami, Rajendra Kumar",
    functionalLeader: "K v s, Deepa",
  },
  AL44856: {
    associateName: "K, Deekshitha",
    function: "Re-work",
    teamLead: "Thami, Rajendra Kumar",
    functionalLeader: "K v s, Deepa",
  },
  AL41948: {
    associateName: "M, Anusha",
    function: "Re-work",
    teamLead: "Thami, Rajendra Kumar",
    functionalLeader: "K v s, Deepa",
  },
  AH85036: {
    associateName: "Aishwarya, P",
    function: "Re-work",
    teamLead: "Thami, Rajendra Kumar",
    functionalLeader: "K v s, Deepa",
  },
  AL53780: {
    associateName: "Mothukuru, Laxmi Brahmani",
    function: "Re-work",
    teamLead: "Thami, Rajendra Kumar",
    functionalLeader: "K v s, Deepa",
  },
  AH84988: {
    associateName: "Nuthalapati, Ramakrishna",
    function: "Re-work",
    teamLead: "Thami, Rajendra Kumar",
    functionalLeader: "K v s, Deepa",
  },
  AH85854: {
    associateName: "Swetha, C",
    function: "Re-work",
    teamLead: "Thami, Rajendra Kumar",
    functionalLeader: "K v s, Deepa",
  },
  AH55219: {
    associateName: "Bazaaru, Swarna",
    function: "Re-work",
    teamLead: "Thami, Rajendra Kumar",
    functionalLeader: "K v s, Deepa",
  },
  AL53783: {
    associateName: "Mounika, Koppula",
    function: "Re-work",
    teamLead: "Thami, Rajendra Kumar",
    functionalLeader: "K v s, Deepa",
  },
  AG55203: {
    associateName: "Thupakula, Manoj Kumar",
    function: "Re-work",
    teamLead: "Thami, Rajendra Kumar",
    functionalLeader: "K v s, Deepa",
  },
  AL45035: {
    associateName: "K, RAKESH.",
    function: "Re-work",
    teamLead: "Thami, Rajendra Kumar",
    functionalLeader: "K v s, Deepa",
  },
  AH85019: {
    associateName: "K S, Mahesh",
    function: "Re-work",
    teamLead: "Thami, Rajendra Kumar",
    functionalLeader: "K v s, Deepa",
  },
  AL52039: {
    associateName: "., Kiran",
    function: "Rosters",
    teamLead: "Y N, Ananda",
    functionalLeader: "K v s, Deepa",
  },
  AL53776: {
    associateName: "A, Manju",
    function: "Rosters",
    teamLead: "Y N, Ananda",
    functionalLeader: "K v s, Deepa",
  },
  AL53319: {
    associateName: "K D, Yashaswi",
    function: "Rosters",
    teamLead: "Y N, Ananda",
    functionalLeader: "K v s, Deepa",
  },
  AL53471: {
    associateName: "Kalas, Mayuresh Dilip",
    function: "Rosters",
    teamLead: "Y N, Ananda",
    functionalLeader: "K v s, Deepa",
  },
  AL53477: {
    associateName: "Kamireddy, Sai jahnavi",
    function: "Rosters",
    teamLead: "Y N, Ananda",
    functionalLeader: "K v s, Deepa",
  },
  AL53323: {
    associateName: "Moger, Komala",
    function: "Rosters",
    teamLead: "Y N, Ananda",
    functionalLeader: "K v s, Deepa",
  },
  AL52949: {
    associateName: "VARUN, MJ",
    function: "Rosters",
    teamLead: "Y N, Ananda",
    functionalLeader: "K v s, Deepa",
  },
  AH85786: {
    associateName: "Mol, Nithya",
    function: "Rosters",
    teamLead: "Y N, Ananda",
    functionalLeader: "K v s, Deepa",
  },
  AH78846: {
    associateName: "Bobba, Hari Babu",
    function: "Rosters",
    teamLead: "Y N, Ananda",
    functionalLeader: "K v s, Deepa",
  },
  AL53504: {
    associateName: "Ann, Klaus J",
    function: "Rosters",
    teamLead: "Y N, Ananda",
    functionalLeader: "K v s, Deepa",
  },
  AH85849: {
    associateName: "B R, Sahana",
    function: "Rosters",
    teamLead: "Y N, Ananda",
    functionalLeader: "K v s, Deepa",
  },
  AL54472: {
    associateName: "Harish, Sadum",
    function: "Rosters",
    teamLead: "Y N, Ananda",
    functionalLeader: "K v s, Deepa",
  },
  AH84951: {
    associateName: "Kamaraj, Masilamani",
    function: "Rosters",
    teamLead: "Y N, Ananda",
    functionalLeader: "K v s, Deepa",
  },
  AH21801: {
    associateName: "G, Harshitha",
    function: "Rosters",
    teamLead: "Y N, Ananda",
    functionalLeader: "K v s, Deepa",
  },
  AL53464: {
    associateName: "M, Deepu",
    function: "Rosters",
    teamLead: "Y N, Ananda",
    functionalLeader: "K v s, Deepa",
  },
  AH72507: {
    associateName: "C, Lavanya",
    function: "Rosters",
    teamLead: "Y N, Ananda",
    functionalLeader: "K v s, Deepa",
  },
}

export function getEmployeeData(domainId: string) {
  return excelData[domainId] || null
}
